# Generated by Django 3.0.5 on 2020-06-08 18:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200602_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='favfoodlist',
            name='nutr_val',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
