# Generated by Django 3.0.5 on 2020-06-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_favfoodlist_nutr_val'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favfoodlist',
            old_name='nutr_val',
            new_name='nutr_vals',
        ),
    ]
