# Generated by Django 3.0.5 on 2020-06-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDescription',
            fields=[
                ('fdc_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('food_category_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'food_description',
                'ordering': ['food_category_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nutrient_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_nutrient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodPortion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('measure_unit_id', models.IntegerField(blank=True, null=True)),
                ('portion_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_portion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeasuringUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'measuring_unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('unit_name', models.TextField(blank=True, null=True)),
                ('nutrient_nbr', models.FloatField(blank=True, null=True)),
                ('rank', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nutrient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrandedFoodCategory',
            fields=[
                ('fdc_id', models.OneToOneField(db_column='fdc_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='foodsearch.FoodDescription')),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('branded_food_category', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'branded_food_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='foodsearch.FoodDescription', to_field='food_category_id')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_category',
                'ordering': ['description'],
                'managed': False,
            },
        ),
    ]
