# Generated by Django 3.0.5 on 2020-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('code', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_category',
                'managed': False,
            },
        ),
    ]
