# Generated by Django 3.0.5 on 2020-04-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsearch', '0002_foodcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddescription',
            options={'managed': False, 'ordering': ['food_category_id']},
        ),
    ]
