# Generated by Django 3.0.5 on 2020-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsearch', '0003_auto_20200424_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandedFoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.BigIntegerField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('serving_size', models.FloatField(blank=True, null=True)),
                ('serving_size_unit', models.TextField(blank=True, null=True)),
                ('branded_food_category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branded_food_category',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'managed': False, 'ordering': ['description']},
        ),
    ]
