# Generated by Django 3.0.5 on 2020-04-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsearch', '0004_auto_20200427_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('fdc_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('data_type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('food_category_id', models.FloatField(blank=True, null=True)),
                ('publication_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_data',
                'managed': False,
            },
        ),
    ]
