# Generated by Django 3.0.5 on 2020-05-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsearch', '0005_fooddata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddata',
            options={'managed': False, 'ordering': ['food_category_id']},
        ),
    ]
