# Generated by Django 3.0.5 on 2020-05-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsearch', '0006_auto_20200504_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodData',
        ),
    ]
