# Generated by Django 3.0.5 on 2020-05-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsearch', '0007_delete_fooddata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandedfoodcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fooddescription',
            options={'managed': True, 'ordering': ['food_category_id']},
        ),
    ]
