# Generated by Django 3.0.5 on 2020-05-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsearch', '0008_auto_20200504_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandedfoodcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fooddescription',
            options={'managed': False, 'ordering': ['food_category_id']},
        ),
    ]
